lib/pages/creature-page.tsx
lib/symbol-context-widget.tsx

This fixes #12 by adding a background color picker to the creature page.
The default background color is `#cccccc`, which I _think_ is mid-gray.
> ![image](https://user-images.githubusercontent.com/124687/108602326-651e9800-736f-11eb-9375-2ac69b74354a.png)

Add configurable bg color to creature page.

---

lib/colors.ts
lib/pages/creature-page.tsx
lib/specs.ts

This fixes #21 by changing the existing "tail" attachment point (`#ff0000`) to be called the "anchor" attachment point, since that's primarily what we're using it for.  It also adds a brand-new "tail" attachment point with color `#be0027`, which is expected to be oriented in the direction the tail should point (not the _opposite_ direction of the tail, which is how the old tail attachment point was oriented).
Note that this change means, for now, that no symbols have tail attachment points.  An error will be logged in the console when viewing the "Creature!" page for now because of this (since the default composition attaches a symbol to the tail), but as soon as Nina updates the SVGs, this should go away.

Add anchor attachment point type.

---

lib/pages/creature-page.tsx
lib/random.test.ts
lib/random.ts
lib/util.test.tsx
lib/util.ts

Fixes #18 by adding a random creature complexity slider. Currently slider values are 0, 1, 2, 3, 4, and bonkers.
> ![image](https://user-images.githubusercontent.com/124687/108796826-ab365000-7557-11eb-8426-05749896506f.png)

Add multiple complexity levels for creature generaiton.

---

lib/bounding-box.test.ts
lib/bounding-box.ts
lib/pages/creature-page.tsx

This adds basic support for nesting (#17).  It does not swap fill/stroke colors based on the position of the nesting box, though. It also only nests a symbol in the eye creature and "bonkers" complexity setting for now--support for nesting in complexity levels 1-4 is forthcoming.
Here's what the eye creature looks like now:
> ![image](https://user-images.githubusercontent.com/124687/109248465-dd43ee00-77b3-11eb-904f-4a460866aa2e.png)
And here's what it looks like with specs showing:
> ![image](https://user-images.githubusercontent.com/124687/109248516-f2b91800-77b3-11eb-9b9e-ace24525e0e9.png)
So the nested symbol is essentially uniformly scaled as much as possible without extending outside the boundaries of its parent's nesting box.

Add basic support for nesting.

---

lib/svg-symbol-metadata.test.ts
lib/svg-symbol-metadata.ts
lib/svg-symbol.tsx
lib/vocabulary-builder.ts
package-lock.json
package.json
svg/_template.toml
svg/eye.toml

This fixes #20 by adding support for TOML-based metadata for symbols.
There's now a template TOML file in `svg/_template.toml` that documents all the different metadata properties.  The file can be copied to match the name of an SVG file (but with a `.toml` extension) and it will be processed by the vocabulary builder when the site is generated.
Currently there are only two properties documented, `always_nest` and `always_be_nested` (as per the needs outlined in https://github.com/toolness/mystic-symbolic/issues/17#issuecomment-786696966), but they don't actually do anything yet (actual support for _using_ the metadata will come in another file).
Right now the TOML files are validated quite stringently: if a file contains the name of a property it doesn't understand, or the type of the …

Add support for TOML symbol metadata.

---

lib/creature-symbol-factory.tsx
lib/creature-symbol.tsx
lib/pages/creature-page.tsx

This refactors `creature-symbol.tsx` so that it doesn't have to rely on awkwardly introspecting `JSX.Element` instances to do its job.  Now all of that mumbo-jumbo, which is only really useful for when we want to manually construct symbols like the eye creature, is encapsulated in `creature-symbol-factory.tsx`.

Massively refactor and simplify creature-symbol.tsx.

---

lib/pages/creature-page.tsx
lib/random.ts

This fixes #39 by adding a "Randomly invert symbols" checkbox.
If the inversion is undesirable, disabling it will keep the existing creature but remove the inversion.
Note that this checkbox is only displayed when the creature complexity isn't bonkers.
> ![image](https://user-images.githubusercontent.com/124687/110226216-51b91400-7ebb-11eb-89d8-660ebe0551b3.png)

Add checkbox for randomly inverting some symbols.

---

lib/pages/creature-page.tsx
lib/specs.ts
lib/svg-symbol-metadata.test.ts
lib/svg-symbol-metadata.ts
lib/test-util.ts
lib/vocabulary-builder.test.ts
svg/_template.toml

This fixes #49 by implementing the `attach_to` metadata property as described at https://github.com/toolness/mystic-symbolic/issues/49#issuecomment-798969203.

Add attach_to metadata.

---

lib/pages/creature-page.tsx

This fixes #53.  Note that this means the eye creature isn't observable from the UI, as moving the slider to "bonkers" shows the eye with parts randomly replaced.  The "pristine" eye creature can still be shown for debugging purposes by adding `&eye=on` to the end of the URL.

Default complexity level to 2.

---

lib/browser-main.tsx
lib/creature-symbol.tsx
lib/pages/creature-page.tsx
lib/pages/mandala-page.tsx
lib/point.ts
lib/svg-transform.tsx
lib/svg-vocabulary.ts

This adds an extremely simple Mandala page (for #24) with a single circle Mandala comprised of several eyes.  The symbol style is configurable, but parameters for the actual Mandala are not (yet).
Doing this also involved factoring out a `<SvgTransforms>` component, which makes setting up SVG transforms a bit easier.
Also moved `getSymbol` of `creature-page.tsx` and into `svg-vocabulary.tsx`, with the new name `getSvgSymbol`.

Add a very basic Mandala page.

---

lib/browser-main.tsx
lib/creature-symbol-factory.tsx
lib/pages/creature-page.tsx
lib/pages/debug-page.tsx

Really the eye creature is only useful for me as a debugging tool, so this moves it over to a separate debug page.
It also removes the whole concept of randomizing the eye creature, mainly because it ignores all the rules set forth in the normal creature randomizer, so it's not terribly useful.
This simplifies the code for `creature-page.tsx` a bunch and hopefully makes it easier to understand.

Move eye creature to a separate debug page.

---

.gitignore
lib/svg-vocabulary.ts
lib/vocabulary-builder.ts

Ugh, we need to write out a TypeScript file instead of importing the JSON directly because otherwise the TS compiler will spend an inordinate amount of time doing type inference, which massively slows down type-checking (especially in IDEs and such).
The TS file actually uses `JSON.parse` on a stringified version of the JSON instead of just inlining the JSON itself because [apparently it's much faster][1].
[1]: https://www.bram.us/2019/11/25/faster-javascript-apps-with-json-parse/

Move SVG vocabulary from JSON to TS.

---

lib/creature-symbol.tsx
lib/pages/mandala-page.tsx
lib/svg-symbol.tsx

This orients the mandala symbols around their anchor point, rather than the center of their bounding box (#24).

Orient mandala symbols around their anchor point.

---

lib/export-svg.tsx
lib/pages/creature-page.tsx
lib/pages/mandala-page.tsx

This fixes #62.
This was a lot easier than I thought it'd be.  I'm pretty sure this kind of solution didn't exist several years ago, but I could be wrong.

Add an 'Export PNG' button

---

index.html
lib/color-widget.tsx
lib/numeric-slider.tsx
lib/pages/mandala-page.tsx
lib/symbol-context-widget.tsx

The key phrase here is **less terrible**, as opposed to **good**.
It doesn't look so bad in this screenshot because I made a mandala that fits on the page and is fully visible.
Right now if the mandala gets too big for the page, it will just overflow and the remainder won't be visible (not even via scrolling).  This is intentional, though, as per @ninapaley's suggestion in https://github.com/toolness/mystic-symbolic/issues/24#issuecomment-809382026:
> I'm hoping you can change the way the image keeps resizing its canvas, and keeps justifying left. Maybe have an oversize canvas with the ring pinned to the center, and all the adjustment sliders on the right? Then they won't disappear if the canvas is too big. Also! I have an idea for an animated cycle that would require the symbols to …

Make mandala UI layout a bit less terrible

---

index.html
lib/checkbox.tsx
lib/pages/creature-page.tsx
lib/pages/mandala-page.tsx
lib/svg-composition-context.tsx
lib/svg-symbol.tsx
lib/symbol-context-widget.tsx

This fixes #67 by making the background color selection/randomization code more DRY via the addition of a new `SvgCompositionContext` and a `CompositionContextWidget`.
It also documents the `SvgSymbolContext` type, and moves the "randomize colors" button closer to the actual colors.

Factor out a SvgCompositionContext.

---

index.html
lib/auto-sizing-svg.tsx
lib/numeric-slider.tsx
lib/pages/mandala-page.tsx
package-lock.json
package.json

This addresses part of #71 by adding some basic animation support to the mandala page.
> ![775f6fa0-598e-4379-81e5-bea1a9e56d5d](https://user-images.githubusercontent.com/124687/113491255-675f3080-949d-11eb-97ae-dde3ccb17439.gif)

Add basic animation support to the mandala page

---

lib/animation.ts
lib/pages/mandala-page.tsx
lib/use-animation.ts

This adds a slider that allows the duration of the mandala animation to be changed (for #71).
In so doing, it also decouples the animation speed from the display's refresh rate.

Make animation duration changeable

---

package-lock.json
package.json

We currently use `rm -rf` in our build script, which is unix-specific. This uses `rimraf` to support Windows.

Use rimraf in build script.

---

lib/pages/debug-page.tsx

This adds a "random color sampling" section to the right side of the debug page:
> ![image](https://user-images.githubusercontent.com/124687/113949108-7b2bcf00-97dc-11eb-8175-a234e070bedb.png)
I'm hoping this will make it easier for @mittimithai to work on his random color code, since it shows a bunch of random colors (100 right now) side-by-side, rather than requiring the developer to constantly click "randomize colors" on mandala/creature to get an idea of what the color spectrum looks like, 3 colors at a time.

Add random color sampling to debug page.

---

lib/pages/creature-page.tsx
lib/pages/mandala-page.tsx
lib/randomizer-widget.tsx
lib/svg-composition-context.tsx

This replaces the "randomize colors" and "randomize" buttons on the creature and mandala pages with a single randomizer widget that allows the user to choose whether they want to randomize the colors, symbols, or both:
> ![image](https://user-images.githubusercontent.com/124687/114110752-3bc9b500-98a6-11eb-8a50-6ba8a72b6936.png)
By default, both colors and symbols are randomized.
Note that this is really only a temporary solution, though: ideally we'll want to provide a more powerful UI that allows users to mark _any_ parameter for randomization, e.g. via "pinning" values or somesuch.

Add randomizer widget

---

lib/pages/mandala-page/core.test.tsx
lib/pages/mandala-page/core.tsx
lib/pages/mandala-page/serialization.ts

This fixes #93 by making the exported mandala filenames include the names of the symbols used in them.  So for example, a mandala with circles made up of the `crown_ornate` symbol and the `heart_break` symbol will now have an exported GIF filename of `mandala-crown_ornate-heart_break.gif`.

Include symbol names in mandala export filename.

---

lib/color-util.test.ts
lib/color-util.ts
lib/pages/mandala-page/serialization.ts
lib/random-colors.test.ts
lib/random-colors.ts
lib/vocabulary-builder.ts

This fixes #129 and also factors out a new function, `clampedBytesToRGBColor()`.

Factor out color-util.ts.

---

.eslintrc
.github/workflows/test.yml
lib/auto-sizing-svg.tsx
lib/browser-main.tsx
lib/page-with-shareable-state.tsx
lib/pages/mandala-page/core.tsx
lib/unique-id.tsx
lib/use-debounced-effect.ts
package-lock.json
package.json

Fixes #128.
A number of hook-related warnings were brought up, which this PR also fixes.  Note that from now on, if there are any warnings raised by the eslint, CI will fail.

Use eslint.

---

lib/pages/mandala-page/mandala-design.avsc.json
lib/pages/mandala-page/mandala-design.v1.avsc.json
lib/pages/mandala-page/serialization.test.ts
lib/pages/mandala-page/serialization.ts
lib/svg-symbol.tsx
lib/symbol-context-widget.tsx
lib/unique-id.tsx
lib/use-debounced-effect.ts
vendor/avro-js.d.ts

This adds a toggle to disable gradients, fixing #140.
On the Mandala page, this changes how our permalinks are structured, but does so in a backwards-compatible way, thanks to [Avro schema evolution][1].  Now the `s` querystring argument is prefixed with a schema version, the latest being `v2`.  If this prefix is missing, it's assumed to be the very first schema version, `v1`, and interpreted accordingly.
[1]: https://martin.kleppmann.com/2012/12/05/schema-evolution-in-avro-protocol-buffers-thrift.html

Add a 'disable gradients' toggle.

---

lib/svg-composition-context.tsx
lib/svg-symbol-metadata.ts
package.json

This makes us actually check TSX files with Prettier (until now we were only checking TS files).
It also re-runs Prettier, although apparently it fixes something in a TS file that was raising a warning, which I find very odd--since TS files were already being checked, I'm not sure how we didn't have a broken build...

Actually check TSX files with Prettier.

---

README.md
assets/symbols/_instructions.md

This adds new documentation for adding/changing symbols at `assets/symbols/_instructions.md` and links to it from `README.md`.

Add documentation on symbols.

---

lib/colors.ts
lib/pages/creature-page.tsx
lib/specs.ts

This adds a new attachment point type called `wildcard` (colored `#000000` in the SVGs) which, as the name suggests, can contain _any_ kind of symbol.
Fixes #187.
@ninapaley I thought "wildcard" might be a more self-evident name than "neutral" but I can change it to "neutral" if you feel strongly about that nomenclature.  Let me know what you think!

Add a 'wildcard' (neutral) attachment point type.

---

assets/symbols/_template.toml
assets/symbols/face_nest.toml
lib/creature-symbol.tsx
lib/svg-symbol-metadata.ts

This adds a new `never_flip_attachments` property to TOML metadata, as discussed in #184, and sets it to `true` for the `face_nest` symbol, resulting in the following kinds of creatures:
> ![image](https://user-images.githubusercontent.com/124687/124523946-0e1dda80-ddc7-11eb-82df-c8cc4f6a4f92.png)

Add never_flip_attachments to TOML metadata.

---

lib/pages/creature-page/core.tsx
lib/pages/creature-page/creature-design.avsc.json
lib/pages/creature-page/serialization.ts

The creature state stored in #210, while quite compact, is also very fragile, because any minor change in our creature generation algorithm or even vocabulary will completely throw off existing serializations.
This attempts to serialize the actual _creature_ created by the generator rather than its random number seed, which will be a larger serialization but also one that is more resilient to future changes in the algorithm and/or vocabulary.  It should also pave the way for tweaking generated creatures.
Note that the previous `v1` schema implemented in #210 is no longer supported--i.e., links that use it will now be broken.  Hopefully this is OK because it hasn't been around for very long, but it was just way too much work to migrate that schema to the new `v2` format.

Implement new Avro schema for creatures

---

lib/pages/creature-page/core.tsx
lib/randomizer-widget.tsx
lib/use-remembered-state.ts

This adds a new `useRememberedState()` React hook that effectively allows us to have user interface elements that "remember" their most recent value, even if the UI itself was unmounted at some point.  (It only works for the lifetime of the page, however, so it doesn't remember values across page reloads; this is intentional, as I didn't want to have to worry about serialization or schema migration.)
The hook is now used in the randomizer widget and for some of the creature page widgets, to ensure that their settings are preserved more often than not.

Remember some widget values more persistently

---

README.md
lib/browser-main.tsx
lib/firebase.tsx
lib/gallery-context.tsx
lib/page-with-shareable-state.tsx
lib/page.css
lib/pages/debug-page.tsx
lib/pages/gallery-page.tsx
lib/pages/index.tsx

This implements an _extremely_ basic Firebase-powered gallery (#26).  At present it's just a list of links to creatures/manadalas that open in new tabs, without preview thumbnails. Or the ability to submit new entries. These features will be forthcoming in future PRs.
As with #215, this decouples the view logic from Firebase so we can use something else in the future if we want.

Implement read-only, text-only gallery

---

lib/loading-indicator.css
lib/loading-indicator.tsx
lib/pages/gallery-page.css
lib/pages/gallery-page.tsx
lib/pages/mandala-page/core.tsx

This adds thumbnails to the gallery (#26).  Mandalas are not currently animated (I'm worried that doing this for lots of mandalas would severely impact performance).  It also adds a loading throbber for the gallery page.
> ![image](https://user-images.githubusercontent.com/124687/131346239-a514d164-ce26-494f-a31c-c2c5c8e29ecf.png)
If a gallery item can't be deserialized, a sad face is shown in place of a thumbnail, with a more detailed explanation on mouseover. For example, if our "clock" symbol were to disappear from our vocabulary (which hopefully won't happen if we do deprecation right, see #221), this would happen (the mouse cursor is at the top-left of the tooltip but was not captured in the screenshot):
> ![image](https://user-images.githubusercontent.com/124687/131682382-f9eca8f4-ac …

Gallery thumbnails

---

lib/page.tsx
lib/pages/creature-page/core.tsx
lib/pages/friendly-page-names.ts
lib/pages/gallery-page.tsx

This fixes #222. Note that it only renames it in the UI, _not_ in the code or the TOML metadata, as that would require a ton of changes, and possibly break old links.

Rename 'creature' to 'cluster'.

---

lib/page-with-shareable-state.tsx
lib/page.css

This fixes #213.  It is not particularly accessible, but since it (hopefully) shouldn't be displayed too often, I'm going to merge it anyways for now--better an inaccessible modal than failing silently.
Screenshot:
> ![image](https://user-images.githubusercontent.com/124687/134573882-d9e969f7-bab9-49bd-a99c-700d68c6cf51.png)

Show error modal if deserialization fails.

---

lib/svg-composition-context.tsx

This adds a "B&W" button to the colors area in the cluster and mandala pages. Clicking it will reset the background, stroke and fill colors to their monochromatic defaults.
> ![image](https://user-images.githubusercontent.com/124687/134903300-5ffcbc27-b499-4e31-8dfc-e5cd76649483.png)
I'm calling the button "B&W" for now to minimize the amount of space the button takes up, since I'd like to add at least one more to that area.  At some point we might want to use a UI that scales a bit better, like a dropdown button.

Add a black & white button.

---

lib/svg-composition-context.tsx

This adds another color-modifying button, "Mono", which makes the fill and stroke colors a minor variation of the background. This makes the composition as a whole monochromatic, hence the name. (Err, at least I _think_ that's an accurate word for what's being done, let me know if I'm wrong!)
> ![image](https://user-images.githubusercontent.com/124687/134908302-bb344459-bf77-4cda-8979-a316659080fc.png)
Here's an example of a design before pressing the button:
> ![mystic-symbolic-creature-rain](https://user-images.githubusercontent.com/124687/134906379-27a1d8f2-b5bf-4049-8122-16eb6885ba62.png)
And here's what it looks like after:
> ![mystic-symbolic-creature-rain(1)](https://user-images.githubusercontent.com/124687/134906413-8b17b99e-74e7-485f-89f1-0694e721af03.png)
In practice, this is …

Add a 'mono' button.

---

lib/auto-sizing-svg.tsx
lib/creature-animator.tsx
lib/creature-symbol.tsx
lib/pages/creature-page/core.tsx

This is a hackneyed attempt to add simple animations to clusters.
I nabbed some nice easing functions from [this venerable gist](https://gist.github.com/gre/1650294).

Add cluster animations.
